### ISSUE TITLE
Reading Hbase Tables with custom namepace

### ISSUE THREAD

**Issue by ghost** [datanucleus/datanucleus-hbase#32]
## Bug Report, attach a testcase using [problem guide](http://www.datanucleus.org/documentation/problem_reporting.html) and state what version the problem occurs in.
So if the table is in a particular namepace other then default. It looks for a cololmn family prepending the namespace and hence throws exception with  org.apache.hadoop.hbase.regionserver.NoSuchColumnFamilyException

**Comment by andyjefferson** [comment]
Aside from the fact that you ignored the template and didnt provide any way of testing whatever this is, this project has little to no resource so people wanting things need to get the code and contribute things.; the only way this will be done

**Comment by ghost** [comment]
Sure I will put a testing framework for it.

**Comment by andyjefferson** [comment]
Year and a half later and still no testcase, so closing this.
